{% set version = "0.1.0" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-gghighlight
  version: {{ version|replace("-", "_") }}

source:
  fn: gghighlight_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/gghighlight_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/gghighlight/gghighlight_{{ version }}.tar.gz
  sha256: c95f68f9bd02af7ce073cbdff41b0a0bc087d754a89b8fcf3c30ae5eaadbd2d5

build:
  number: 0
  skip: true  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base
    - r-dplyr >0.7.0
    - r-ggplot2 >=2.2.0
    - r-ggrepel
    - r-magrittr
    - r-purrr
    - r-rlang

  run:
    - r-base
    - r-dplyr >0.7.0
    - r-ggplot2 >=2.2.0
    - r-ggrepel
    - r-magrittr
    - r-purrr
    - r-rlang

test:
  commands:
    - $R -e "library('gghighlight')"  # [not win]
    - "\"%R%\" -e \"library('gghighlight')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=gghighlight
  license: MIT
  summary: Make it easier to explore data with highlights.
  license_family: MIT

extra:
  recipe-maintainers:
    - cbrueffer
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
