{% set version = "0.3.1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-gghighlight
  version: {{ version|replace("-", "_") }}

source:
  fn: gghighlight_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/gghighlight_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/gghighlight/gghighlight_{{ version }}.tar.gz
  sha256: b1b0a5c928df7e655aa7ca9c99bd57c9b97aef2a212c2a82079f15b88e7925f0

build:
  noarch: generic
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
  host:
    - r-base
    - r-dplyr >0.7.0
    - r-ggplot2 >=3.0.0
    - r-ggrepel
    - r-magrittr
    - r-purrr
    - r-rlang
    - r-tibble
  run:
    - r-base
    - r-dplyr >0.7.0
    - r-ggplot2 >=3.0.0
    - r-ggrepel
    - r-magrittr
    - r-purrr
    - r-rlang
    - r-tibble

test:
  commands:
    - $R -e "library('gghighlight')"           # [not win]
    - "\"%R%\" -e \"library('gghighlight')\""  # [win]

about:
  home: https://github.com/yutannihilation/gghighlight/
  license: MIT
  license_file: LICENSE
  summary: Make it easier to explore data with highlights.
  license_family: MIT

extra:
  recipe-maintainers:
    - conda-forge/r
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
