{% set version = "0.3.2" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-gghighlight
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/gghighlight_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/gghighlight/gghighlight_{{ version }}.tar.gz
  sha256: 5b543e550acb216beb1f80d2a41c9fb13c88ee29932185b98238fc9e35b1af2f

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-dplyr >=1.0.0
    - r-ggplot2 >=3.0.0
    - r-ggrepel
    - r-lifecycle
    - r-purrr
    - r-rlang
    - r-tibble
  run:
    - r-base
    - r-dplyr >=1.0.0
    - r-ggplot2 >=3.0.0
    - r-ggrepel
    - r-lifecycle
    - r-purrr
    - r-rlang
    - r-tibble

test:
  commands:
    - $R -e "library('gghighlight')"           # [not win]
    - "\"%R%\" -e \"library('gghighlight')\""  # [win]

about:
  home: https://github.com/yutannihilation/gghighlight/
  license: MIT
  summary: Make it easier to explore data with highlights.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r

# Type: Package
# Package: gghighlight
# Title: Highlight Lines and Points in 'ggplot2'
# Version: 0.3.1
# Authors@R: person(given = "Hiroaki", family = "Yutani", role = c("aut", "cre"), email = "yutani.ini@gmail.com", comment = c(ORCID = "0000-0002-3385-7233"))
# Description: Make it easier to explore data with highlights.
# License: MIT + file LICENSE
# URL: https://github.com/yutannihilation/gghighlight/
# BugReports: https://github.com/yutannihilation/gghighlight/issues
# Depends: ggplot2 (>= 3.0.0), R (>= 3.2.0)
# Imports: dplyr (>= 1.0.0), ggrepel, lifecycle, purrr, rlang, tibble
# Suggests: knitr, rmarkdown, sf, testthat, vdiffr (>= 0.3.0)
# VignetteBuilder: knitr
# RdMacros: lifecycle
# Encoding: UTF-8
# LazyData: true
# RoxygenNote: 7.1.1
# Config/testthat/edition: 3
# NeedsCompilation: no
# Packaged: 2020-12-12 03:18:34 UTC; yutani
# Author: Hiroaki Yutani [aut, cre] (<https://orcid.org/0000-0002-3385-7233>)
# Maintainer: Hiroaki Yutani <yutani.ini@gmail.com>
# Repository: CRAN
# Date/Publication: 2020-12-12 06:10:02 UTC
