{% set version = '0.1.0' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-gghighlight
  version: {{ version|replace("-", "_") }}

source:
  fn: gghighlight_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/gghighlight_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/gghighlight/gghighlight_{{ version }}.tar.gz
  sha256: c95f68f9bd02af7ce073cbdff41b0a0bc087d754a89b8fcf3c30ae5eaadbd2d5

build:
  noarch: generic
  merge_build_host: True  # [win]
  number: 1001
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
  host:
    - r-base
    - r-dplyr >0.7.0
    - r-ggplot2 >=3.0.0
    - r-ggrepel
    - r-magrittr
    - r-purrr
    - r-rlang
    - r-tibble
  run:
    - r-base
    - r-dplyr >0.7.0
    - r-ggplot2 >=3.0.0
    - r-ggrepel
    - r-magrittr
    - r-purrr
    - r-rlang
    - r-tibble

test:
  commands:
    - $R -e "library('gghighlight')"           # [not win]
    - "\"%R%\" -e \"library('gghighlight')\""  # [win]

about:
  home: https://github.com/yutannihilation/gghighlight/
  license: MIT
  summary: Make it easier to explore data with highlights.
  license_family: MIT

extra:
  recipe-maintainers:
    - conda-forge/r
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
