travis:
  secure:
    BINSTAR_TOKEN: TdK7SQhHZ7I8eIrlrKAu+kxm0LkghSgiWWPq4A0yVkoWW0WWROLBdFFcgwj2xXaekqEC2gE7ifSWH2S/f5KBfZgRUD7WVYCJPyzxVPaiVzNE70rQSZ++3764RMJSBZSoDljCkMtFS6k/jMOLCW2vipxsDRQ6N8t0sGH9ipEt/idgjwZdpLW3K2q6JiG5c+0ABnhVlmeSI/YjQ29TntFY5G7DmK92dn8NLJJkVIQB+p8yeBtkUHdE7PzxtIcokMLlu0DlUW9eolns36/zGs70lJpWbDu6bdDCSOq+hkvo6KjmsHzUSRWk8X2+Zf6KlG9lFvv1PqEwB/9SvuT20Nk1bYVtCNyX92ariWZnc0nQLlLxG3ch5MYJ88o4XE9qjSOftfyDhVw7W1CcW8EJ8dnKJ8RvnuGG9cNbcKJvPfQ/usa9tltPyWIyKztMBxMoQ8qFbM48bFlek8g8pUdAo/sX5wgVI5ioIljnuhvp9bkkBnEQL0TlQrP5aVubYN0dtUruER36Sq6XXZ7HdkeOrgiTXr84spL1KdWTq/4FSlxUB8gMXVYjnu41yoXN5JtJNSP+iS3LTZPTP9X5mn72s4Oifazb8NFY1pLnJAB/hJZu9VKo0Evwo73VzyE66KpGbEgqaqn1gYBz7GYgelNFKefTbqMgL3ObydIHNqZk9RD02Ec=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
