travis:
  secure:
    BINSTAR_TOKEN: FoAIeaEyHXol4a2O9Bb9fqFB7uoOlqfA9H/QiQ6+iVZyhvE69xvxJDLpN8y+kt/U1f4jOR4OCai0fVicdHz4RIeAEd4YHQceOrHbHUPyh8PbYJlAapP7mWVXbceO6DusrLWWd6M+2r2A6kDto+eN9i0i/LSSSE05QPtyN3ooRXyGA0FfzDOqoSM5AM2xULt07HECS3UeyL7guVfIffybPeK/enszTM4Gfkh9D4HUtXlrtq5F0kQCriNVpdlT1TUhieyHXRVT1rn2OVrzhdKdC+2g+obo8afPWz+tMwKbhR6AXX3YIajz9ZV2unDqBMl1ejDQSabivVU0J6+D8k39NS13yhWSlTkpM5cJozjU1UJEDZJZ7K/1YxPOomx5AJk8nAN8Blxhk6l8q8mHMpRrNzrUmEgrm0OOazxjuA4BwAs65YWu0dUyOv3qk5qje2XYxoWTRv67UuxHW9r3pgks6IU99YnPXLWRwRePPholgXVFVpKAShLug1lVAKtYWZv2fqZE9GdfeBMKk84rpEUyAkKMR2wtcZQAOGWVivIPU8teP+RzrABRqJEt2YbOERuVyPBXEnhILeocfY5aa3f3TxK2Td47dr/qkuYHHwUVNTyif9k5lgV3CfBnBqGYJznm1aze+OMl1y6bkQ+JtXyE+/uTuUhzxopFBId8pd9ra8Y=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
