appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: SwONkkXakwwZtK6c31qYoTVHrlOjWteVb5DEdAmTd5q171j/L2Zu+fEuVphthqHrBhVVGJezLyD1U+4skJNjwO93FPzjF+7knx01sgfytdaXT3VqLE+aA1fZ9ZuA4AhOMTugM8bIyUG4rncNRreOhalaCEzTYzsBA3uz5szK0xFaJUgOPIoJuipBQZuEZ7rzfRhPqWZBtlZEdbYbRxF+X55gyZda0LRZJ+hBKviz8PhNBrov1chYNIymBMqDyzwHe2NRo9RVqUoQ5E11SyMcD6Do1/LNaG/p+g+aNso8Af2YKzi06dLC+BElmNumxxHf7yQo3YXXqv7sZu66GSYJ/lFh+UWNXztXjYqMVpttYmTIbzVpmprwiEE8nb0REkm0uljh7e6C+u4E9f2t5SID4GFn3ET4cujOMs/ZckVN3Ex8nCko9hGND+2LYPYDv7iwShFHhD/2mEZ2zz04T9lIoujM9SuijRZnPpwVh+8FLjjpjOSc1nfMwxnbKowPirwTfstsME6SRVElbA/gxRRXQOrnXeh/KIXmGxTBYqgQxima/BDPGSNnbXREQtOYbkpOa40dByskdIblKB3MgGe/V/siDxIUCj2/3w4KbZXTXHHgrnQCKwcpsI5X4kCDS4GKMZ2v2Q+swjsZQNTAPcg94k2TLEL/JictMJBfubvMvCE=}
