travis:
  secure:
    BINSTAR_TOKEN: HZnQNXI6a5YB2UVzqaBhBwTMC8LMfIGiisi1WxZDUK5ncZeVDyaQzUTp57K4c7vLFl5tUZDzIJfl20sW62nyr56HalHPNlMcpgDKPVw+yihMksc3/6lDGDDAoSHXBpQcHYQVQHKd6rGsbQR17qVUW1Ja9UeJsTBZosC0R2C0YE/cfwyl53w6Uk0DVafqden3mXuh+WN21pY8HrYJ/JP75+im3gowf1q2UYWUUXzl0C4hQJRk11GL0K09MfHwHjlql/oiQEbOm8QTahc3E+7jaI6ZsY4VxfoGOcq0/HhUiLpe2m5350e56tgtAkwc1x9F0dy4hfDsKxzRsksfz3bZQwToZeOdK6jBWKXdUB0ml9fFAUKVSuBzURnL1kscp/7JH5Mz8gldhppMzW69LQif+DcGIho6UBWqKU8oQvDPaRHNvhkWM4NLbltVd2Ed96FT0IlZ/KmWoA/+X7QlDv9Si8fZRoEGSwYT+tnDBW5IknkVmQ+SETQoAp2bVS57y/NhET4qQi4xkLL827LCqW4pohGvOKVynESn4Axw5udHa6dtbCgoxbK4llhx6smUW5wO/4Q0iVXCkOdkgXyC+xz0+EJlEn3o0/+NtDBJZnBx5O1BHpjHAnvvE9605w2qefCTNvy6wrkQZ66cuU6hPFRpCbM3qe/9DeYKpwg8NFQ/q0I=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
